const beats=[
 {title:'AFTER HOURS',genre:'AFRO R&B',bpm:104,key:'F# MINOR',duration:'2:43',price:29.99,color:'#9b6b4f',desc:'Late-night drums, velvet keys and a little danger.'},
 {title:'NO SIGNAL',genre:'TRAP',bpm:142,key:'C MINOR',duration:'2:18',price:39.99,color:'#536366',desc:'For the moments when silence says enough.'},
 {title:'VELVET',genre:'R&B',bpm:88,key:'D MINOR',duration:'3:02',price:29.99,color:'#8a5a6d',desc:'Soft edges. Heavy feelings. No compromise.'},
 {title:'MIDNIGHT',genre:'AFROBEATS',bpm:112,key:'A MINOR',duration:'2:54',price:34.99,color:'#756b42',desc:'The city looks different after midnight.'},
 {title:'FALLING',genre:'POP',bpm:120,key:'G MAJOR',duration:'2:31',price:24.99,color:'#596f7b',desc:'A widescreen instrumental for a close-up feeling.'},
 {title:'SAINT',genre:'HIP-HOP',bpm:90,key:'E MINOR',duration:'2:47',price:49.99,color:'#70634a',desc:'Gold dust on the snare. Built for a statement.'},
 {title:'OUTSIDE',genre:'DRILL',bpm:140,key:'B MINOR',duration:'2:21',price:39.99,color:'#53684c',desc:'Leave the comfort zone at the door.'},
 {title:'RED ROOM',genre:'AFRO R&B',bpm:98,key:'C# MINOR',duration:'3:12',price:44.99,color:'#863f37',desc:'Warm bass, cold light, a room full of ideas.'}
];
let cart=[],current=-1,isPlaying=false,progress=0,timer;
const app=document.querySelector('#app');const player=document.querySelector('#player');
function headerFooter(){return `<div class="marquee"><span>SAINTYVES — PRODUCER — SOUND DESIGN — INSTRUMENTALS — SAINTYVES — PRODUCER — SOUND DESIGN — INSTRUMENTALS — </span></div><footer class="footer"><div><h2>SAINTYVES</h2><p>Built for artists.<br>Crafted by SAINTYVES.</p></div><p><a href="#contact" data-route="contact">Contact</a><br><a href="#about" data-route="about">About</a><br><a href="#beats" data-route="beats">The vault</a></p></footer>`}
function beatCard(b,i){return `<article class="beat-card" data-index="${i}"><div class="cover" style="--cover:${b.color}"><button class="play-card" aria-label="Play ${b.title}">${current===i&&isPlaying?'Ⅱ':'▶'}</button></div><div class="beat-info"><div class="beat-top"><strong>${b.title}</strong><span>$${b.price.toFixed(2)}</span></div><div class="beat-meta"><span>${b.genre}</span><span>${b.bpm} BPM</span><span>${b.key}</span></div></div></article>`}
function home(){app.innerHTML=`<div class="page"><section class="hero"><div><span class="eyebrow">Independent producer / est. 2024</span><h1>YOUR<br><em>SOUND.</em><br>YOUR<br>WORLD.</h1><p class="hero-copy">Premium instrumentals crafted for artists who refuse to sound ordinary.</p><div class="hero-actions"><button class="button button-light" data-route="beats">Explore the vault <span>↗</span></button><button class="button" data-play="0">Listen now <span>▶</span></button></div></div><div class="hero-art"><span class="art-meta one">104 BPM / F# MIN</span><span class="art-meta two">AFRO R&B / 02:43</span><div class="wave">${Array.from({length:38},(_,i)=>`<i style="--h:${18+Math.abs(Math.sin(i*.8))*45}px"></i>`).join('')}</div></div></section><section class="intro"><h2>MORE THAN<br>BEATS. <span>IT’S<br>A SOUND.</span></h2><p>SAINTYVES creates distinctive instrumentals for artists, songwriters and creators building worlds of their own. Every beat is a starting point. The rest is yours.</p></section><section><div class="section-head"><div><span class="eyebrow">01 / The vault</span><h2>The latest drops</h2></div><p>Fresh sounds from the<br>SAINTYVES vault.</p></div><div class="beat-grid">${beats.map(beatCard).join('')}</div></section></div>${headerFooter()}`;bind();}
function beatsPage(){app.innerHTML=`<div class="page"><section class="library-head"><div><span class="eyebrow">02 / Catalog</span><h1>FIND<br>YOUR<br>SOUND.</h1></div><p>Explore a curated collection of premium instrumentals, ready for whatever comes next.</p></section><div class="filters"><button class="filter active" data-filter="ALL">ALL</button>${['AFROBEATS','AFRO R&B','TRAP','HIP-HOP','R&B','DRILL','POP'].map(x=>`<button class="filter" data-filter="${x}">${x}</button>`).join('')}</div><div class="beat-grid" id="library-grid">${beats.map(beatCard).join('')}</div></div>${headerFooter()}`;bind();}
function detail(i){const b=beats[i];app.innerHTML=`<div class="page"><section class="about-grid"><div><span class="eyebrow">Beat / ${String(i+1).padStart(2,'0')}</span><div class="cover" style="--cover:${b.color};max-width:560px;margin-top:28px"><button class="play-card" data-play="${i}">▶</button></div></div><div class="story"><span class="eyebrow">${b.genre} / ${b.bpm} BPM / ${b.key}</span><h1 style="font-size:clamp(55px,8vw,120px);margin-top:25px">${b.title}</h1><p>${b.desc}</p><div class="stats"><div><strong>${b.duration}</strong><span>DURATION</span></div><div><strong>$${b.price}</strong><span>STARTING AT</span></div></div><div style="display:grid;gap:12px;margin-top:35px"><button class="button" data-license="BASIC" data-index="${i}">Basic / MP3 / $${b.price.toFixed(2)} ↗</button><button class="button button-light" data-license="PREMIUM" data-index="${i}">Premium / WAV / $${(b.price+30).toFixed(2)} ↗</button><button class="button" data-license="EXCLUSIVE" data-index="${i}">Exclusive / Stems / $199.99 ↗</button></div><p style="font-size:12px;margin-top:30px">Need something custom? <a href="#contact" data-route="contact" style="color:var(--acid)">Work directly with SAINTYVES.</a></p></div></section></div>${headerFooter()}`;bind();document.querySelectorAll('[data-license]').forEach(x=>x.onclick=()=>{const price=x.dataset.license==='BASIC'?b.price:x.dataset.license==='PREMIUM'?b.price+30:199.99;cart.push({title:b.title,license:x.dataset.license,price});renderCart();openCart();toast(`${x.dataset.license} license added to cart.`)})}
function about(){app.innerHTML=`<div class="page"><section class="about-grid"><div><span class="eyebrow">03 / The story</span><h1>THE SOUND<br>BEHIND<br>THE <em>SOUND.</em></h1></div><div class="story"><p>SAINTYVES is a producer, sound designer and student of the details that make a record feel like a place.</p><p>From warm analog texture to drums that cut through the noise, every instrumental is made for artists who want more than background music. They want a world to step into.</p><div class="stats"><div><strong>50+</strong><span>BEATS CREATED</span></div><div><strong>100+</strong><span>ARTISTS SERVED</span></div><div><strong>12</strong><span>GENRES</span></div></div><button class="button button-light" data-route="contact" style="margin-top:35px">Work with SAINTYVES ↗</button></div></section></div>${headerFooter()}`;bind();}
function contact(){app.innerHTML=`<div class="page"><section class="contact-grid"><div><span class="eyebrow">04 / Start a conversation</span><h1>LET’S MAKE<br><em>SOMETHING.</em></h1></div><form class="contact-form" id="contact-form"><label>NAME<input required placeholder="Your name"></label><label>EMAIL<input required type="email" placeholder="you@email.com"></label><label>PROJECT TYPE<input placeholder="Single, EP, campaign..." /></label><label>MESSAGE<textarea placeholder="Tell me about the sound you're looking for."></textarea></label><button class="button button-light">Send inquiry ↗</button></form></section></div>${headerFooter()}`;bind();document.querySelector('#contact-form').onsubmit=e=>{e.preventDefault();toast('Inquiry sent — we’ll be in touch.');e.target.reset()};}
function admin(){app.innerHTML=`<div class="login"><div class="login-box"><span class="eyebrow">Private access</span><h1>SAINTYVES<br>STUDIO</h1><form id="login-form"><input type="email" placeholder="Email" required><input type="password" placeholder="Password" required><button class="button button-light">Enter studio ↗</button></form></div></div>`;bind();document.querySelector('#login-form').onsubmit=e=>{e.preventDefault();dashboard()};}
function dashboard(section='dashboard'){app.innerHTML=`<div class="admin"><aside class="admin-side"><h2>SAINTYVES<br><span style="color:var(--acid)">STUDIO</span></h2>${['dashboard','beats','upload','orders','analytics','settings'].map(x=>`<a href="#admin/${x}" class="${section===x?'active':''}" data-admin="${x}">${x}</a>`).join('')}</aside><section class="admin-main">${adminContent(section)}</section></div>`;bind();}
function adminContent(section){if(section==='upload')return `<span class="eyebrow">Studio / New release</span><h1>Upload beat.</h1><p>Put something new into the world.</p><div class="upload-grid"><form class="upload-form" id="upload-form"><label>Title<input required placeholder="Beat title"></label><label>Genre<select><option>Afro R&B</option><option>Trap</option><option>Hip-Hop</option></select></label><label>BPM<input placeholder="104"></label><label>Key<input placeholder="F# Minor"></label><label>Description<textarea placeholder="The feeling behind the sound..."></textarea></label><button class="button button-light">Publish to vault ↗</button></form><div class="upload-box"><div><span>＋</span>DROP ARTWORK HERE<br><small>1200 × 1200 / JPG, PNG</small></div></div></div>`;if(section==='beats')return `<span class="eyebrow">Studio / Catalog</span><h1>Manage beats.</h1><p>24 releases in the vault.</p><div class="admin-table">${beats.map(b=>`<div class="table-row"><strong>${b.title}</strong><span>${b.genre}</span><span>${b.bpm} BPM</span><span class="status">Published</span><span>$${b.price}</span></div>`).join('')}</div>`;if(section==='orders')return `<span class="eyebrow">Studio / Commerce</span><h1>Orders.</h1><p>Recent movement through the vault.</p><div class="admin-table">${[['#SY-1048','Maya Johnson','AFTER HOURS','PREMIUM','$59.00'],['#SY-1047','Jordan Lee','RED ROOM','BASIC','$29.00'],['#SY-1046','Nia Carter','SAINT','EXCLUSIVE','$199.00']].map(x=>`<div class="table-row"><strong>${x[0]}</strong><span>${x[1]}</span><span>${x[2]}</span><span class="status">Paid</span><span>${x[4]}</span></div>`).join('')}</div>`;return `<span class="eyebrow">Studio / Overview</span><h1>Good evening,<br>SAINTYVES.</h1><p>Here’s what’s happening with your sound.</p><div class="stat-grid"><div class="stat-card"><small>Total beats</small><strong>24</strong></div><div class="stat-card"><small>Total sales</small><strong>$4,820</strong></div><div class="stat-card"><small>This month</small><strong>$1,240</strong></div><div class="stat-card"><small>Top beat</small><strong>After Hours</strong></div></div><span class="eyebrow">Revenue / last 8 weeks</span><div class="chart">${[35,49,42,68,55,82,73,96].map((h,i)=>`<i class="bar" style="--height:${h}%" data-label="W${i+1}"></i>`).join('')}</div>`}
function openCart(){document.querySelector('#cart-drawer').classList.add('open');document.querySelector('.drawer-backdrop').classList.add('open');renderCart()}function closeCart(){document.querySelector('#cart-drawer').classList.remove('open');document.querySelector('.drawer-backdrop').classList.remove('open')}
function renderCart(){document.querySelector('#cart-count').textContent=cart.length;document.querySelector('#drawer-count').textContent=`(${cart.length})`;document.querySelector('#cart-items').innerHTML=cart.length?cart.map((x,i)=>`<div class="cart-line"><div><small>${x.license}</small><strong>${x.title}</strong></div><div><strong>$${x.price.toFixed(2)}</strong><button class="remove-line" data-remove="${i}">Remove</button></div></div>`).join(''):`<div class="empty-cart">Your vault is empty.<br><a href="#beats" data-route="beats">Explore the latest drops →</a></div>`;document.querySelector('#cart-total').textContent=`$${cart.reduce((s,x)=>s+x.price,0).toFixed(2)}`;bind()}
function play(i){current=i;isPlaying=!isPlaying;const b=beats[i];player.classList.add('show');document.querySelector('#player-title').textContent=b.title;document.querySelector('#player-art').textContent=b.title.slice(0,2);document.querySelector('#duration').textContent=b.duration;document.querySelector('#play-btn').textContent=isPlaying?'Ⅱ':'▶';if(isPlaying){clearInterval(timer);timer=setInterval(()=>{progress=(progress+1)%101;document.querySelector('#progress').value=progress},1000)}else clearInterval(timer);document.querySelectorAll('.beat-card').forEach((c,j)=>{const btn=c.querySelector('.play-card');if(btn)btn.textContent=j===i&&isPlaying?'Ⅱ':'▶'})}
function toast(msg){const t=document.querySelector('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2400)}
function bind(){document.querySelectorAll('[data-route]').forEach(x=>x.onclick=e=>{e.preventDefault();location.hash=x.dataset.route});document.querySelectorAll('[data-play]').forEach(x=>x.onclick=()=>play(+x.dataset.play));document.querySelectorAll('.beat-card').forEach(x=>{x.onclick=e=>{if(e.target.classList.contains('play-card')){play(+x.dataset.index);return}detail(+x.dataset.index)}});document.querySelectorAll('[data-filter]').forEach(x=>x.onclick=()=>{document.querySelectorAll('.filter').forEach(y=>y.classList.remove('active'));x.classList.add('active');const val=x.dataset.filter;document.querySelectorAll('.beat-card').forEach(c=>c.style.display=val==='ALL'||c.querySelector('.beat-meta').textContent.includes(val)?'block':'none')});document.querySelectorAll('[data-admin]').forEach(x=>x.onclick=e=>{e.preventDefault();dashboard(x.dataset.admin)});document.querySelectorAll('[data-remove]').forEach(x=>x.onclick=()=>{cart.splice(+x.dataset.remove,1);renderCart()});const f=document.querySelector('#upload-form');if(f)f.onsubmit=e=>{e.preventDefault();toast('Beat published to the vault.');f.reset()}}
function route(){const r=location.hash.replace('#','')||'home';if(r.startsWith('admin/'))dashboard(r.split('/')[1]);else if(r==='beats')beatsPage();else if(r==='about')about();else if(r==='contact')contact();else if(r==='admin')admin();else home()}
const cartTrigger=document.querySelector('.cart-trigger');if(cartTrigger)cartTrigger.onclick=openCart;const closeDrawer=document.querySelector('.close-drawer');if(closeDrawer)closeDrawer.onclick=closeCart;const backdrop=document.querySelector('.drawer-backdrop');if(backdrop)backdrop.onclick=closeCart;const playBtn=document.querySelector('#play-btn');if(playBtn)playBtn.onclick=()=>current>=0&&play(current);const nextBtn=document.querySelector('#next-btn');if(nextBtn)nextBtn.onclick=()=>play((current+1)%beats.length);const prevBtn=document.querySelector('#prev-btn');if(prevBtn)prevBtn.onclick=()=>play((current-1+beats.length)%beats.length);const checkoutBtn=document.querySelector('.checkout-btn');if(checkoutBtn)checkoutBtn.onclick=()=>cart.length?toast('Checkout is ready for your payment flow.'):toast('Add a license to continue.');window.addEventListener('hashchange',route);route();
